### ISSUE TITLE
Баги при тестировании

### ISSUE THREAD

**Issue by paulloft** [zzqar/auction_symfony#1]
1. Невозможно развернуть новый проект из-за некорректных миграций.
2. Невозможно зарегистрировать нового пользователя. Ошибка доступа.
3. После добавления новго лота страница не перезагружается/не редиректится, форма не сбрасывается.
4. Нельзя добавить изображение товара
5. Можно установить отрицательную начальную стоимость у товара, в результате с товаром нельзя ничего сделать
6. Фатал при переходе на карточку товара
7. Фатал при попытке завершить аукцион товара у которого не ставок
8. Фатал при попытке отменить аукцион товара у которого не ставок
8. Фатал при попытке запустить задачу app:goods:check
9. Невозможно купить товар по последней ставке. app:goods:check тупо отменяет аукцион не смотря на то, что была ставка
10. Можно выставить дату окончания аукциона в прошлом при этом ставки так же принимаются

11. Форма добавления лота зачем-то открыватся в новом окне
12. Отсутсвует роутинг на главной странице. Открывается дефолтная страница симфони
13. Невалидная ссылка на регистрацию внизу формы авторизации

**Comment by zzqar** [comment]
Исправил

**Comment by zzqar** [comment]
Исправил
