### ISSUE TITLE
Баги при тестировании #2

### ISSUE THREAD

**Issue by paulloft** [zzqar/auction_symfony#2]
форма добавления лота: 
если через инспектор изменить тип поля цена на text, то по прежнему можно добавить лот с отрицательной стоимостью
так же можно добавить лот с датой окончания в прошлом
вместо картинки можно загрузить всё что угодно
если ввести невалидное (например текстом) значение цены, то форма закроется, а при повторном открытии в ней будет ошибка поля

**Comment by zzqar** [comment]
исправил
